"""Verify the geometric identification R(M) = H*(U_M) where
   U_M = (P^1)^n \\ (coordinate subspace arrangement of M's circuits).

For each test matroid M, compute:
  - R(M) Hilbert series (= f-vector with top-degree truncation due to circuits)
  - H*(U_M) Hilbert series (= H*((P^1)^n) / (matroid ideal))

For matroidal Δ = IN(M):
  H*((P^1)^n) = k[x_1, ..., x_n] / (x_i^2)         — exterior face ring of boolean complex.
  R(M) = k[x_1, ..., x_n] / (x_i^2, x_C : C circuit) — exterior face ring of IN(M).
  R(M) = H*((P^1)^n) / I_M where I_M = ideal generated by circuit monomials.

This is also = H*(U_M) for U_M = (P^1)^n \\ ⋃ Z_C, by Goresky-MacPherson.

Equivalence between geometric "Z_C" subvariety and algebraic "x_C" relation:
  Z_C = {z_i = 0 ∀ i ∈ C} ⊂ (P^1)^n, codim |C|. Its class [Z_C] in H*((P^1)^n)
  equals ∏_{i ∈ C} x_i.

Removing the union ⋃ Z_C: by Gysin / inclusion-exclusion, H*(complement) = quotient
by the ideal generated by {[Z_C]} = matroid ideal.

GOAL of this script: confirm the f-vector of R(M) matches the predicted Hilbert
series of (P^1)^n / matroid-ideal, and identify the Lefschetz operator mult-ω
geometrically.
"""

from __future__ import annotations
import sys
from itertools import combinations
sys.path.insert(0, '/workspace-vast/asving/qlc/computations')
from gpu_rank import Matroid, M_Kn, Vamos
from test_hard_lefschetz_x import x_sets, free_sum, single_triangle


def find_circuits(M):
    """Minimal dependent sets of M."""
    indep = M.indep
    circuits = []
    for k in range(1, M.n + 1):
        for S in combinations(range(M.n), k):
            S = frozenset(S)
            if S in indep:
                continue
            # check minimal
            is_min = all((S - frozenset([e])) in indep for e in S)
            if is_min:
                circuits.append(S)
    return circuits


def f_vector_of_R(M):
    """Hilbert function of R(M) = k[x_i]/(x_C, x_i^2).
    Direct enumeration: dim R(M)_d = # indep sets of size d (= M.f[d])."""
    return list(M.f)


def compute_geometric_hilbert(M):
    """Compute Hilbert series of H*((P^1)^n) / (matroid ideal).
    Equivalent computation to R(M) by Goresky-MacPherson.
    Returns: list of dimensions by degree.

    H*((P^1)^n) basis = squarefree monomials in n variables (since x_i^2 = 0).
    Quotient by matroid ideal: remove monomials divisible by any circuit-monomial.
    A monomial x_S (squarefree, S ⊆ [n]) is killed iff S contains some circuit.
    Equivalently: x_S survives iff S is independent.

    So dim of quotient at degree |S| = # independent S of size |S| = f_{|S|}(M).
    Matches algebraic R(M).
    """
    return [len(M.by_size.get(d, [])) for d in range(M.n + 1)]


def verify(M, label):
    print(f"\n{'='*60}")
    print(f"  {label}: n={M.n}, rank={M.rank}")
    print(f"{'='*60}")
    f_R = f_vector_of_R(M)
    f_geom = compute_geometric_hilbert(M)
    circuits = find_circuits(M)
    print(f"  Circuits: {sorted([sorted(c) for c in circuits])[:5]}{'...' if len(circuits) > 5 else ''}")
    print(f"  R(M) Hilbert (algebraic): {f_R}")
    print(f"  H*((P^1)^n)/I_M (geometric): {f_geom}")
    match = (f_R == f_geom)
    print(f"  Match: {'✓ EQUAL — R(M) = H*(U_M)' if match else '✗ MISMATCH'}")

    # X-restriction
    xv = [len(x_sets(M, k)) for k in range(M.n + 1)]
    while xv and xv[-1] == 0: xv.pop()
    x_supp_start = next((i for i, v in enumerate(xv) if v > 0), 0)
    print(f"  X-vector: {xv[x_supp_start:] if x_supp_start < len(xv) else []}  (support starts at {x_supp_start})")
    print(f"  R(M)|_X is the subspace of R(M) at grades [{x_supp_start}, {len(xv)-1}],")
    print(f"  with basis {{x_S : S ∈ X(M), |S|=k}} at each grade k.")


def main():
    matroids = [
        (Matroid.uniform(2, 3), "U(2,3) Triangle"),
        (Matroid.uniform(3, 4), "U(3,4)"),
        (Matroid.uniform(3, 5), "U(3,5)"),
        (Matroid.uniform(4, 5), "U(4,5)"),
        (M_Kn(4), "M(K_4)"),
        (single_triangle(2), "U(2,3)⊕U(2,2)"),
    ]
    for M, label in matroids:
        verify(M, label)

    print(f"\n{'='*60}")
    print("STRUCTURAL UPSHOT")
    print(f"{'='*60}")
    print("""
For every loopless matroid M on n elements:
  R(M) = H*((P^1)^n minus matroid arrangement) = H*(U_M).
  This is Goresky-MacPherson / De Longueville for coordinate subspace
  arrangement complements where the arrangement is defined by minimal
  non-faces (= circuits) of IN(M).

The mult-by-ω = Σ x_i operator on R(M) corresponds geometrically to
multiplication by the Aut(M)-invariant Kähler class on (P^1)^n
(= sum of pullback Kähler classes from each P^1 factor), restricted to
the quotient R(M) = H*((P^1)^n) / matroid-ideal.

Hard Lefschetz on (P^1)^n with this ω is classical. The question:
does HL DESCEND to R(M) (or to R(M)|_X)?

Key fact: the matroid ideal is closed under mult-ω. Proof: for x_C with
C a circuit, x_i · x_C is either 0 (if i ∈ C, since x_i^2 = 0) or
x_{C∪{i}} which contains C, hence is in the matroid ideal.

So mult-ω descends to R(M). But HL on the quotient is non-trivial:
the quotient R(M) is NOT Gorenstein (Poincaré duality fails) for non-uniform M.

The X-restriction R(M)|_X is the sub-piece where Poincaré duality
(via the bilinear pairing) DOES hold, with INDEFINITE Hodge signature.
This is consistent with R(M)|_X being a specific weight-pure piece of
H*(U_M) on which a SAITO-type mixed Hodge module Lefschetz statement holds.

Conjecture (refined geometric form):
  The symmetric ω = Σ x_i is a Lefschetz element on R(M) restricted to
  R(M)|_X, with HL inherited from (P^1)^n via a Saito mixed-Hodge-module
  argument on the open variety U_M.
""")


if __name__ == "__main__":
    main()
